### ISSUE TITLE
[Analytics] Remove tracking from builders

### ISSUE THREAD

**Issue by KittySparkles** [sheepyard/stormbound-kitty#859]
- [x] `/calculators/value/*` (6b7eb03f5cba9428f98f57a4ffbedfa57a58b176)
- [x] `/card/*` (8ef5db42445b196e4c8c60af852b580d4597f976, 77703c805b66d7f4e67fdb11181eb3b5045ec055)
- [x] `/card/*/display` (8ef5db42445b196e4c8c60af852b580d4597f976, 77703c805b66d7f4e67fdb11181eb3b5045ec055)
- [x] `/deck/*` (#874)
- [x] `/deck/*/detail` (a2fb6e18)
- [x] `/deck/*/dry-run` (a2fb6e18)
- [x] `/list/*` (#875)
- [x] `/list/*/display` (a2fb6e18)
- [x] `/quest/*` (6b7eb03f5cba9428f98f57a4ffbedfa57a58b176)
- [x] `/simulators/battle/*` (#865)
- [x] `/simulators/battle/*/display` (#865)
- [x] `/simulators/books/*` (6b7eb03f5cba9428f98f57a4ffbedfa57a58b176)
- [x] `/simulators/draft/*` (6b7eb03f5cba9428f98f57a4ffbedfa57a58b176)
